TEST_VALUE:
  name: dev_test

FEISHU_CONFIG:
  FEISHU_URL: https://open.feishu.cn/open-apis
  FEISHU_API_HOST: https://open.feishu.cn
  FEISHU_APP_ID: cli_a318163712d2d00e
  FEISHU_APP_SECRET: ImuxVY6eXmXyCGG3hZGOvraPaLUp1zjF

MONGODB_CONFIG:
  name: "fast_gateway_test"          # 自定义次数据库链接名称
  type: mongodb                      # 数据库链接类型
  url: "mongodb://admin:123456@47.99.153.97:27017/?authSource=admin"   # 数据库链接地址 mongodb://admin:123456@47.99.153.97:27017/gateway?authSource=admin
  username: "admin"                   # 数据库链接用户名
  password: "123456"                 # 数据库链接密码
  database: "gateway"      # 数据库名
  entities: "mongo"                  # 自定义加载类型
  logging: false                     # 数据库打印日志
  synchronize: true                  # 是否开启同步数据表功能

MYSQL_CONFIG:
  name: "user-test"
  type: "mysql"
  host: "47.99.153.97"
  port: 3306
  username: "root"
  password: "123456"
  database: "user-test"
  entities: "mysql" # 这里的命名一定要跟 MongoDB 里面的配置命名区分开
  synchronize: true

REDIS_CONFIG:
  host: "47.99.153.97"  # redis 链接
  port: 6379         # redis 端口
  auth:       # redis 连接密码
  db: 0              # redis 数据库
